// Auto-generated by scripts/scan-themes.js — do not edit manually
// Re-run: node scripts/scan-themes.js

export interface ThemeFeatures {
  supportedModes: ('light' | 'dark' | 'system')[];
  showCoverImage: boolean;
  showBio: boolean;
}

export interface ThemeConfig {
  id: string;
  name: string;
  author: string;
  version: string;
  features: ThemeFeatures;
}

export const BUILTIN_THEMES: Record<string, ThemeConfig> = {
  "default": {
      "id": "default",
      "name": "默认主题",
      "author": "System",
      "version": "1.0.0",
      "features": {
        "supportedModes": [
          "light",
          "dark",
          "system"
        ],
        "showCoverImage": true,
        "showBio": true
      }
    } as const satisfies ThemeConfig,
  "wechat-classic": {
      "id": "wechat-classic",
      "name": "微信经典",
      "author": "daocatt",
      "version": "1.0.0",
      "features": {
        "supportedModes": [
          "light"
        ],
        "showCoverImage": false,
        "showBio": true
      }
    } as const satisfies ThemeConfig,
};

export const DEFAULT_THEME_CONFIG: ThemeConfig = {
    "id": "default",
    "name": "默认主题",
    "author": "System",
    "version": "1.0.0",
    "features": {
      "supportedModes": [
        "light",
        "dark",
        "system"
      ],
      "showCoverImage": true,
      "showBio": true
    }
  } as const satisfies ThemeConfig;

export const THEME_LIST: ThemeConfig[] = Object.values(BUILTIN_THEMES);

export const VALID_THEME_IDS: string[] = Object.keys(BUILTIN_THEMES);

export const THEME_CSS_IMPORTS: string[] = [
  "@/themes/default/theme.css",
  "@/themes/wechat-classic/theme.css"
];
