const fs = require("fs");
const path = require("path");

const ROOT_DIR = path.resolve(__dirname, "..");
const THEMES_DIR = path.join(ROOT_DIR, "src", "themes");
const OUTPUT_FILE = path.join(ROOT_DIR, "src", "lib", "theme-registry.gen.ts");

function generate() {
  if (!fs.existsSync(THEMES_DIR)) {
    fs.mkdirSync(THEMES_DIR, { recursive: true });
  }

  const entries = fs
    .readdirSync(THEMES_DIR, { withFileTypes: true })
    .filter((d) => d.isDirectory());

  const themes = [];

  for (const entry of entries) {
    const configPath = path.join(THEMES_DIR, entry.name, "theme-config.json");
    const cssPath = path.join(THEMES_DIR, entry.name, "theme.css");

    if (!fs.existsSync(configPath)) {
      console.warn(`[theme-scanner] Skipping "${entry.name}": no theme-config.json`);
      continue;
    }
    if (!fs.existsSync(cssPath)) {
      console.warn(`[theme-scanner] Skipping "${entry.name}": no theme.css`);
      continue;
    }

    try {
      const raw = fs.readFileSync(configPath, "utf-8");
      const config = JSON.parse(raw);
      if (!config.id || !config.name) {
        console.warn(`[theme-scanner] Skipping "${entry.name}": theme-config.json missing id or name`);
        continue;
      }
      themes.push({
        ...config,
        _dirName: entry.name,
      });
    } catch (e) {
      console.warn(`[theme-scanner] Skipping "${entry.name}": invalid theme-config.json - ${e.message}`);
    }
  }

  const lines = [
    "// Auto-generated by scripts/scan-themes.js — do not edit manually",
    "// Re-run: node scripts/scan-themes.js",
    "",
    "export interface ThemeFeatures {",
    "  supportedModes: ('light' | 'dark' | 'system')[];",
    "  showCoverImage: boolean;",
    "  showBio: boolean;",
    "}",
    "",
    "export interface ThemeConfig {",
    "  id: string;",
    "  name: string;",
    "  author: string;",
    "  version: string;",
    "  features: ThemeFeatures;",
    "}",
    "",
  ];

  const themeEntries = themes.map((t) => {
    const { _dirName, ...config } = t;
    const json = JSON.stringify(config, null, 2)
      .split("\n")
      .map((line, i) => (i === 0 ? line : "    " + line))
      .join("\n");
    return `  "${config.id}": ${json} as const satisfies ThemeConfig`;
  });

  lines.push(`export const BUILTIN_THEMES: Record<string, ThemeConfig> = {`);
  for (const entry of themeEntries) {
    lines.push(entry + ",");
  }
  lines.push("};");
  lines.push("");

  const defaultTheme = themes.find((t) => t.id === "default");
  if (defaultTheme) {
    const { _dirName, ...config } = defaultTheme;
    const json = JSON.stringify(config, null, 2)
      .split("\n")
      .map((line, i) => (i === 0 ? line : "  " + line))
      .join("\n");
    lines.push(`export const DEFAULT_THEME_CONFIG: ThemeConfig = ${json} as const satisfies ThemeConfig;`);
  } else {
    lines.push(`export const DEFAULT_THEME_CONFIG: ThemeConfig = BUILTIN_THEMES["default"];`);
  }
  lines.push("");

  lines.push(
    `export const THEME_LIST: ThemeConfig[] = Object.values(BUILTIN_THEMES);`
  );
  lines.push("");

  lines.push(
    `export const VALID_THEME_IDS: string[] = Object.keys(BUILTIN_THEMES);`
  );
  lines.push("");

  const cssImports = themes.map((t) => `@/themes/${t._dirName}/theme.css`);
  lines.push(
    `export const THEME_CSS_IMPORTS: string[] = ${JSON.stringify(cssImports, null, 2)};`
  );
  lines.push("");

  fs.writeFileSync(OUTPUT_FILE, lines.join("\n"), "utf-8");

  const cssOutputFile = path.join(ROOT_DIR, "src", "lib", "theme-css.gen.ts");
  const cssLines = [
    "// Auto-generated by scripts/scan-themes.js — do not edit manually",
    "// Re-run: node scripts/scan-themes.js",
    "",
  ];
  for (const imp of cssImports) {
    cssLines.push(`import "${imp}";`);
  }
  cssLines.push("");
  fs.writeFileSync(cssOutputFile, cssLines.join("\n"), "utf-8");

  const names = themes.map((t) => t.id);
  console.log(`[theme-scanner] Generated theme-registry.gen.ts with themes: [${names.join(", ")}]`);
}

generate();
